---
title: "Introduction to business intelligence in public statistics (Power BI)"
subtitle: "Day 1"  
author: 
  - "Øyvind Bruer-Skarsbø (SSB)"
  - "Carl Franklin Corneil (SSB)"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE
)
```

```{r metathis, echo=FALSE}
library(metathis)
meta() %>%
  meta_name("github-repo" = "https://github.com/skars82/slides") %>% 
  meta_social(
    title = "Introduction to business intelligence in public statistics (Power BI)",
    description = paste(
      "3-day course in how a business intelligence tool lik Power BI can be used in public statistics. ",
      "Course held by European Statitical Training Programme (ESTP) in april of 2021."
    ),
    url = "https://skars82.github.io/slides/estp_course_powerbi/day1.html#1",
    image = "https://github.com/skars82/slides/tree/master/docs/estp_course_powerbi/pictures/twitter_slide.png",
    image_alt = paste(
      "Title slide of day 1 of ESTP-course in Power BI:", 
      "How can Power BI be utilized in public statistics.", 
      "Estp-course held in april of 2021."
    ),
    og_type = "website",
    og_author = "Øyvind Bruer-Skarsbø",
    twitter_card_type = "summary_large_image",
    twitter_creator = "@YSkarsb",
    twitter_site = "@YSkarsb"
  )
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo(primary_color = "#1F4257", secondary_color = "#F97B64")
```

```{r xaringan-tile-view, echo=FALSE}
xaringanExtra::use_tile_view()
```

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

---

## Introduction to the course






